name: vy_fixed_decimal
description: FixedDecimal class allows to manager numbers with a fixed decimal part length,
  while Money class allows to manage currencies.
  Both classes works on top of the Decimal one by Alexandre Ardhuin
version: 1.0.3
homepage: https://github.com/giorgiofran/vy_fixed_decimal

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  decimal : ^3.2.0
  rational: ^2.2.0
  intl: ^0.20.0
  quiver: ^3.0.0

dev_dependencies:
  test: ^1.16.4
  lints: ^6.0.0

